#http://en.wikibooks.org/wiki/Ada_Programming/All_Keywords
#http://en.wikibooks.org/wiki/Ada_Programming/Attributes

reserved = {
	# 'ada':'ADA_RESERVED', 
	'exception':'EXCEPTION',
	'abs':'ABS',
	'reverse':'REVERSE',
	'do':'DO',
	'when':'WHEN',
	'null':'NuLL',
	'and':'AND',
	'constant':'CONSTANT',
	'mod':'MOD',
	'separate':'SEPARATE',
	'select':'SELECT',
	'task':'TASK',
	'new':'NEW',
	'private':'PRIVATE',
	'with':'WITH',
	'subtype':'SUBTYPE',
	'access':'ACCESS',
	'out':'OUT',
	'abort':'ABORT',
	'until':'UNTIL',
	'of':'OF',
	'range':'RANGE',
	'tagged':'TAGGED',
	'body':'BODY',
	'generic':'GENERIC',
	'at':'AT',
	'return':'RETURN',
	'renames':'RENAMES',
	'pragma':'PRAGMA',
	'use':'USE',
	'rem':'REM',
	'or':'OR',
	'record':'RECORD',
	'if':'IF',
	'xor':'XOR',
	'protected':'PROTECTED',
	'goto':'GOTO',
	'accept':'ACCEPT',
	'in':'IN',
	'delay':'DELAY',
	'else':'ELSE',
	'package':'PACKAGE',
	# 'interface':'INTERFACE',
	# 'overriding':'OVERRIDING',
	'begin':'BEGIN',
	'entry':'ENTRY',
	'loop':'LOOP',
	'type':'TYPE',
	'case':'CASE',
	'declare':'DECLARE',
	'then':'THEN',
	'others':'OTHERS',
	'delta':'DELTA',
	'while':'WHILE',
	'is':'IS',
	'elsif':'ELSIF',
	'for':'FOR',
	'procedure':'PROCEDURE',
	# 'synchronized':'SYNCHRONIZED',
	'abstract':'ABSTRACT',
	'not':'NOT',
	'exit':'EXIT',
	# 'some':'SOME',
	'terminate':'TERMINATE',
	'function':'FUNCTION',
	'requeue':'REQUEUE',
	'end':'END',
	'limited':'LIMITED',
	'all':'ALL',
	'aliased':'ALIASED',
	'raise':'RAISE',
	'array':'ARRAY',
	'digits':'DIGITS',
	'lambda':'LAMBDA'
	# '\'Value':'ATTR_VALUE',
	# '\'Val':'ATTR_VAL',
	# '\'Model_Mantissa':'ATTR_MODEL_MANTISSA',
	# '\'Body_Version':'ATTR_BODY_VERSION',
	# '\'Remainder':'ATTR_REMAINDER',
	# '\'Fraction':'ATTR_FRACTION',
	# '\'Delta':'ATTR_DELTA',
	# '\'Machine_Rounds':'ATTR_MACHINE_ROUNDS',
	# '\'Safe_Small':'ATTR_SAFE_SMALL',
	# '\'Epsilon':'ATTR_EPSILON',
	# '\'Machine_Radix':'ATTR_MACHINE_RADIX',
	# '\'Partition_ID':'ATTR_PARTITION_ID',
	# '\'Machine_Emin':'ATTR_MACHINE_EMIN',
	# '\'Model_Small':'ATTR_MODEL_SMALL',
	# '\'Version':'ATTR_VERSION',
	# '\'Write':'ATTR_WRITE',
	# '\'Safe_Emax':'ATTR_SAFE_EMAX',
	# '\'Modulus':'ATTR_MODULUS',
	# '\'Input':'ATTR_INPUT',
	# '\'Denorm':'ATTR_DENORM',
	# '\'First':'ATTR_FIRST',
	# '\'Callable':'ATTR_CALLABLE',
	# '\'Class':'ATTR_CLASS',
	# '\'Overlaps_Storage':'ATTR_OVERLAPS_STORAGE',
	# '\'Identity':'ATTR_IDENTITY',
	# '\'Safe_Large':'ATTR_SAFE_LARGE',
	# '\'Signed_Zeros':'ATTR_SIGNED_ZEROS',
	# '\'Storage_Size':'ATTR_STORAGE_SIZE',
	# '\'Scale':'ATTR_SCALE',
	# '\'Max':'ATTR_MAX',
	# '\'First_Bit':'ATTR_FIRST_BIT',
	# '\'Machine_Emax':'ATTR_MACHINE_EMAX',
	# '\'Component_Size':'ATTR_COMPONENT_SIZE',
	# '\'Small':'ATTR_SMALL',
	# '\'Round':'ATTR_ROUND',
	# '\'Caller':'ATTR_CALLER',
	# '\'Exponent':'ATTR_EXPONENT',
	# '\'Access':'ATTR_ACCESS',
	# '\'Succ':'ATTR_SUCC',
	# '\'Compose':'ATTR_COMPOSE',
	# '\'Address':'ATTR_ADDRESS',
	# '\'Definite':'ATTR_DEFINITE',
	# '\'Aft':'ATTR_AFT',
	# '\'Wide_Width':'ATTR_WIDE_WIDTH',
	# '\'Position':'ATTR_POSITION',
	# '\'Leading_Part':'ATTR_LEADING_PART',
	# '\'Safe_First':'ATTR_SAFE_FIRST',
	# '\'External_Tag':'ATTR_EXTERNAL_TAG',
	# '\'Model_Emin':'ATTR_MODEL_EMIN',
	# '\'Safe_Last':'ATTR_SAFE_LAST',
	# '\'Has_Same_Storage':'ATTR_HAS_SAME_STORAGE',
	# '\'Size':'ATTR_SIZE',
	# '\'Adjacent':'ATTR_ADJACENT',
	# '\'Model_Epsilon':'ATTR_MODEL_EPSILON',
	# '\'Machine_Rounding':'ATTR_MACHINE_ROUNDING',
	# '\'Digits':'ATTR_DIGITS',
	# '\'Wide_Image':'ATTR_WIDE_IMAGE',
	# '\'Truncation':'ATTR_TRUNCATION',
	# '\'Large':'ATTR_LARGE',
	# '\'Machine_Overflows':'ATTR_MACHINE_OVERFLOWS',
	# '\'Old':'ATTR_OLD',
	# '\'Mantissa':'ATTR_MANTISSA',
	# '\'Rounding':'ATTR_ROUNDING',
	# '\'Count':'ATTR_COUNT',
	# '\'Min':'ATTR_MIN',
	# '\'Pred':'ATTR_PRED',
	# '\'Image':'ATTR_IMAGE',
	# '\'Wide_Wide_Image':'ATTR_WIDE_WIDE_IMAGE',
	# '\'Wide_Value':'ATTR_WIDE_VALUE',
	# '\'Width':'ATTR_WIDTH',
	# '\'Fore':'ATTR_FORE',
	# '\'Last':'ATTR_LAST',
	# '\'Machine':'ATTR_MACHINE',
	# '\'Wide_Wide_Width':'ATTR_WIDE_WIDE_WIDTH',
	# '\'Length':'ATTR_LENGTH',
	# '\'Bit_Order':'ATTR_BIT_ORDER',
	# '\'Terminated':'ATTR_TERMINATED',
	# '\'Floor':'ATTR_FLOOR',
	# '\'Read':'ATTR_READ',
	# '\'Machine_Mantissa':'ATTR_MACHINE_MANTISSA',
	# '\'Priority':'ATTR_PRIORITY',
	# '\'Output':'ATTR_OUTPUT',
	# '\'Unbiased_Rounding':'ATTR_UNBIASED_ROUNDING',
	# '\'Model':'ATTR_MODEL',
	# '\'Alignment':'ATTR_ALIGNMENT',
	# '\'Pos':'ATTR_POS',
	# '\'Base':'ATTR_BASE',
	# '\'Valid':'ATTR_VALID',
	# '\'Ceiling':'ATTR_CEILING',
	# '\'Max_Size_In_Storage_Elements':'ATTR_MAX_SIZE_IN_STORAGE_ELEMENTS',
	# '\'Range':'ATTR_RANGE',
	# '\'Scaling':'ATTR_SCALING',
	# '\'Tag':'ATTR_TAG',
	# '\'Mod':'ATTR_MOD',
	# '\'Stream_Size':'ATTR_STREAM_SIZE',
	# '\'Last_Bit':'ATTR_LAST_BIT',
	# '\'Wide_Wide_Value':'ATTR_WIDE_WIDE_VALUE',
	# '\'Storage_Pool':'ATTR_STORAGE_POOL',
	# '\'Max_Aligment_For_Allocation':'ATTR_MAX_ALIGMENT_FOR_ALLOCATION',
	# '\'Constrained':'ATTR_CONSTRAINED',
	# '\'Unchecked_Access':'ATTR_UNCHECKED_ACCESS',
	# '\'Result':'ATTR_RESULT',
	# '\'Copy_Sign':'ATTR_COPY_SIGN',
	# 'storage_element':'STORAGE_ELEMENT_TYPE',
 #    'storage_array':'STORAGE_ARRAY_TYPE',
 #    'storage_offset':'STORAGE_OFFSET_TYPE',
 #    'integer':'INT_TYPE',
 #    'duration':'DURATION_TYPE',
 #    'character':'CHARACTER_TYPE',
 #    'float':'FLOAT_TYPE',
 #    'string':'STRING_TYPE',
 #    'storage_count':'STORAGE_COUNT_TYPE',
 #    'address':'ADDRESS_TYPE'
}