#http://en.wikibooks.org/wiki/Ada_Programming/All_Keywords
#http://en.wikibooks.org/wiki/Ada_Programming/Attributes

reserved = {
	# 'ada':'ADA_RESERVED', 
	# 'exception':'EXCEPTION',
	# 'abs':'ABS',
	# 'reverse':'REVERSE',
	# 'do':'DO',
	# 'when':'WHEN',
	'null':'NuLL',
	'and':'AND',
	# 'constant':'CONSTANT',
	'mod':'MOD',
	# 'separate':'SEPARATE',
	# 'select':'SELECT',
	# 'task':'TASK',
	# 'new':'NEW',
	# 'private':'PRIVATE',
	'with':'WITH',
	# 'subtype':'SUBTYPE',
	'access':'ACCESS',
	# 'out':'OUT',
	# 'abort':'ABORT',
	# 'until':'UNTIL',
	'of':'OF',
	# 'range':'RANGE',
	# 'tagged':'TAGGED',
	'body':'BODY',
	# 'generic':'GENERIC',
	# 'at':'AT',
	'return':'RETURN',
	# 'renames':'RENAMES',
	'pragma':'PRAGMA',
	'use':'USE',
	# 'rem':'REM',
	'or':'OR',
	'record':'RECORD',
	'if':'IF',
	# 'xor':'XOR',
	# 'protected':'PROTECTED',
	# 'goto':'GOTO',
	# 'accept':'ACCEPT',
	'in':'IN',
	# 'delay':'DELAY',
	'else':'ELSE',
	# 'package':'PACKAGE',
	# 'interface':'INTERFACE',
	# 'overriding':'OVERRIDING',
	'begin':'BEGIN',
	# 'entry':'ENTRY',
	'loop':'LOOP',
	'type':'TYPE',
	# 'case':'CASE',
	# 'declare':'DECLARE',
	'then':'THEN',
	# 'others':'OTHERS',
	# 'delta':'DELTA',
	'while':'WHILE',
	'is':'IS',
	# 'elsif':'ELSIF',
	'for':'FOR',
	'procedure':'PROCEDURE',
	# 'synchronized':'SYNCHRONIZED',
	# 'abstract':'ABSTRACT',
	# 'not':'NOT',
	# 'exit':'EXIT',
	# 'some':'SOME',
	# 'terminate':'TERMINATE',
	'function':'FUNCTION',
	# 'requeue':'REQUEUE',
	'end':'END',
	# 'limited':'LIMITED',
	# 'all':'ALL',
	# 'aliased':'ALIASED',
	# 'raise':'RAISE',
	'array':'ARRAY',
	# 'digits':'DIGITS',
	'lambda':'LAMBDA'
	# 'storage_element':'STORAGE_ELEMENT_TYPE',
 #    'storage_array':'STORAGE_ARRAY_TYPE',
 #    'storage_offset':'STORAGE_OFFSET_TYPE',
 #    'integer':'INT_TYPE',
 #    'duration':'DURATION_TYPE',
 #    'character':'CHARACTER_TYPE',
 #    'float':'FLOAT_TYPE',
 #    'string':'STRING_TYPE',
 #    'storage_count':'STORAGE_COUNT_TYPE',
 #    'address':'ADDRESS_TYPE'
}